apiVersion: v1
kind: Secret
metadata:
  name: global-secret
type: Opaque
data:
  
  GOOGLE_CLIENT_ID: MjEzMjAxMjU3MDkyLWpvcmdlY3M4NmpiMmMxcXQ5cTFyOXZrZGM0cnJldGduLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLS1EamxsclhOWm11aUc4MHVRbm9qX1h1eFRnamI=
  EMAIL_PASSWORD: amFraUFtZW4xMj8=
  ALPHA_VANTAGE_API_KEY: RjdSWFlMWk81WElaTlozVQ==
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzcw==
